export const HomeScreen = "/"
export const CreateCollection = "/CreateCollection"
export const CreateNewItem = "/CreateNewItem"
export const GettingStarted = "/GettingStarted"
export const SearchCollections = "/SearchCollections"
export const Staking = "/Staking"
export const TopNFTs = "/TopNFTs"